# Generated by Django 4.2.7 on 2023-11-25 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='works/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('tech', 'tech'), ('design', 'design'), ('social', 'social'), ('media', 'media'), ('scale', 'scale')], max_length=50)),
                ('disc', models.TextField(blank=True, null=True)),
                ('videos', models.FileField(blank=True, null=True, upload_to='works/videos/')),
            ],
        ),
        migrations.CreateModel(
            name='WorkSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('subcate_image', models.ImageField(upload_to='subimages')),
            ],
        ),
        migrations.CreateModel(
            name='WorkSub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.worksubcategory')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.work')),
            ],
        ),
        migrations.CreateModel(
            name='WorkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.image')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work.work')),
            ],
        ),
        migrations.AddField(
            model_name='work',
            name='cats',
            field=models.ManyToManyField(related_name='cats', through='work.WorkSub', to='work.worksubcategory'),
        ),
        migrations.AddField(
            model_name='work',
            name='images',
            field=models.ManyToManyField(related_name='+', through='work.WorkImage', to='work.image'),
        ),
        migrations.AddField(
            model_name='image',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_images', to='work.work'),
        ),
    ]
